services:
  backend:
    build:
      context: ./shop-backend
      dockerfile: Dockerfile
    container_name: shop-backend-server
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: postgres:15-alpine
    container_name: shop-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: shop_user
      POSTGRES_PASSWORD: S2a4Dg5Hhe4TfSn7NYm*
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
      - ./shop-database/init:/docker-entrypoint-initdb.d:ro